### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by Yub0** [pitkley/docker-netbox#19]
Hello,

It's possible to add LDAP support ?
I see the repo has ldap tag but no ldap var in the configuration file.

Thanks

**Comment by pitkley** [comment]
LDAP-support was included with PR #18, which was merged into the [`ldap` branch](https://github.com/pitkley/docker-netbox/tree/ldap) and for which the [Docker hub image/tag `pitkley/netbox:ldap`](https://hub.docker.com/r/pitkley/netbox/tags) exists.

Looking at the [Netbox documentation regarding LDAP](https://netbox.readthedocs.io/en/stable/installation/4-ldap/#configuration), a `ldap_config.py` has to be created and put into the `netbox/netbox/` directory. For this image that would mean creating the file, and mounting it to the path `/usr/src/netbox/netbox/ldap_config.py`.

You can do that by adding the following snippet to the `netbox` container definition in the `docker-compose.yml` like so:

```yaml
services:
    ...
    netbox:
        ...
        volumes:
            - /path/on/host/to/ldap_config.py:/usr/src/netbox/netbox/ldap_config.py:ro
```

LDAP-support in this image was an external contribution and I'm not using the feature myself, so I'm not 100-percent sure if that is all that is required. Maybe @rcmurphy can chime in here?
