### ISSUE TITLE
Persistence Volumes

### ISSUE THREAD

**Issue by A75G** [pitkley/docker-netbox#21]
Hello,
Thanks for all the hard work you make.
I wanted to ask about Persistence Volumes for netbox is it viable for this docker

Thanks

**Comment by pitkley** [comment]
Hi @A75G, thanks for the kind words and your interest!

The simplest way to achieve persistence is by using a docker volume within the `docker-compose.yml` file:

```yml
version: '2'

services:
    db:
        image: postgres:9.5
        environment:
            - POSTGRES_USER=netbox
            - POSTGRES_PASSWORD=netbox
        volumes:
            - postgres_data:/var/lib/postgresql/data

    netbox:
        image: pitkley/netbox
        depends_on:
            - db
        ports:
            - "8000:8000"
        environment:
            - "ALLOWED_HOSTS=netbox.dev localhost"
            - "DB_HOST=db"
            - "DB_NAME=netbox"
            - "DB_USER=netbox"
            - "DB_PASS=netbox"
            - "SECRET_KEY=" # change me

volumes:
    postgres_data:
```

Or printed as a diff to [the `docker-compose.example.yml` provided in this repo](https://github.com/pitkley/docker-netbox/blob/develop/docker-compose.example.yml):

```diff
--- docker-compose.yml
+++ docker-compose.yml
@@ -6,6 +6,8 @@
         environment:
             - POSTGRES_USER=netbox
             - POSTGRES_PASSWORD=netbox
+        volumes:
+            - postgres_data:/var/lib/postgresql/data
 
     netbox:
         image: pitkley/netbox
@@ -21,3 +23,5 @@
             - "DB_PASS=netbox"
             - "SECRET_KEY=" # change me
 
+volumes:
+    postgres_data:
```

Since all the data is stored in PostgreSQL, adding a volume to the data-directory of the Postgres-container is sufficient to achieve persistence. (I am running Netbox like this and it hasn't failed me once. :+1:)

I hope this helps?
