### ISSUE TITLE
Username and password?

### ISSUE THREAD

**Issue by absolutejam** [pitkley/docker-netbox#9]
Hey!

Not sure if I missed something in the README, but is there a default username/password, or can one defined? I can't currently get in, and I've followed the instructions (incl. `createsuperuser`).

My dev docker-compose looks like:
```
version: '2.4'

services:
  netbox:
    image: "pitkley/netbox"
    hostname: "netbox"
    container_name: "netbox"
    environment:
      ALLOWED_HOSTS: "*"
      DB_HOST: "postgres"
      DB_NAME: "netbox"
      DB_USER: "netbox"
      DB_PASS: "netbox"
      SECRET_KEY: "redacted"
    networks:
      db:
      proxy:
    labels:
      - traefik.port=8000
      - traefik.protocol=http
      - traefik.frontend.rule=Host:netbox.x.y.z
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
      - traefik.docker.network=proxy

  postgres:
    image: "postgres:9.5"
    hostname: "netbox_postgres"
    container_name: "netbox_postgres"
    environment:
      POSTGRES_USER: "netbox"
      POSTGRES_PASSWORD: "netbox"
      DB_PASS: "netbox"
    volumes:
      - "./volumes/postgres_data:/var/lib/postgresql/data"
    networks:
      db:

networks:
  proxy:
    external: True
  db:
```

Regards
